### ISSUE TITLE
[Предложение]

### ISSUE THREAD

**Issue by Mairam213** [space-sunrise/fire-station#161]
**Ваш запрос функции связан с проблемой/ошибкой? Опишите, пожалуйста.**

**Опишите желаемое**

**Дополнительный контекст**

```
- type: alertLevels
  id: stationAlerts
  defaultLevel: green
  levels:
    green:
      announcement: alert-level-green-announcement
      color: Green
      emergencyLightColor: LawnGreen
      shuttleTime: 600
    blue:
      announcement: alert-level-blue-announcement
      sound: /Audio/Misc/bluealert.ogg
      color: DodgerBlue
      forceEnableEmergencyLights: true
      emergencyLightColor: DodgerBlue
      shuttleTime: 600
    gray:
      announcement: alert-level-gray-announcement
      sound: /Audio/Misc/notice1.ogg
      color: Gray
      emergencyLightColor: Gray
      forceEnableEmergencyLights: true
      shuttleTime: 600
    yellow:
      announcement: alert-level-yellow-announcement
      sound: /Audio/Misc/notice1.ogg
      color: Yellow
      emergencyLightColor: Goldenrod
      forceEnableEmergencyLights: true
      shuttleTime: 600
    red:
      announcement: alert-level-red-announcement
      sound: /Audio/Misc/redalert.ogg
      color: Red
      emergencyLightColor: Red
      forceEnableEmergencyLights: true
      shuttleTime: 600 #No reduction in time as we don't have swiping for red alert like in /tg/. Shuttle times are intended to create friction, so having a way to brainlessly bypass that would be dumb.
    White:
      announcement: alert-level-white-announcement
      selectable: false
      sound:
        path: /Audio/_Sunrise/Misc/siren.ogg # Sunrise-Edit
        params:
          volume: -2
      disableSelection: true
      color: White
      emergencyLightColor: White
      forceEnableEmergencyLights: true
    delta:
      announcement: alert-level-delta-announcement
      selectable: false
      sound:
        path: /Audio/Misc/delta_alt.ogg
        params:
          volume: -3
      disableSelection: true
      color: DarkRed
      emergencyLightColor: DarkRed
      forceEnableEmergencyLights: true
      shuttleTime: 2400
    coldsilver:
      announcement: alert-level-coldsilver-announcement
      selectable: false
      sound:
        path: /Audio/Misc/notice1.ogg
        params:
          volume: -3
      disableSelection: true
      color: White
      emergencyLightColor: White
      forceEnableEmergencyLights: true
      shuttleTime: 2400
    foxtrot:
      announcement: alert-level-foxtrot-announcement
      selectable: false
      sound:
        path: /Audio/Misc/notice1.ogg
        params:
          volume: -2
      disableSelection: true
      color: DarkViolet
      emergencyLightColor: DarkViolet
      forceEnableEmergencyLights: true
      shuttleTime: 2400
```

Сами коды угроз.

```
alert-level-announcement = Уважаемый персонал. Ситуационный код теперь { $name }! { $announcement }
alert-level-unknown = Неизвестный.
alert-level-unknown-instructions = Неизвестно.
alert-level-green = Зелёный
alert-level-green-announcement = Угроза была локализована или полностью устранена. Можно возвращаться на свои рабочие места.
alert-level-green-instructions = Выполняйте и соблюдайте свой рабочий стандарт.
alert-level-blue = Синий
alert-level-blue-announcement = Внимание всем боевыем юнитам. На территории Д-блока зафиксированы массовые беспорядки. Службе Безопасности Административной Зоне приступить к локализации угрозы.
alert-level-blue-instructions = Гражданскому персоналу запрещено приближаться к Д-блоку и контактировать с Д-классом. Вся исследовательская деятельность должна быть приостановлена.
alert-level-red = Красный
alert-level-red-announcement = Зафиксировано нарушение условий содержания 2-х и более SCP-объектов. Всему гражданскому персоналу проследовать в безопасное место. Службе Безопасности локализовать угрозу.
alert-level-red-instructions = Гражданскому персоналу проследовать в бункер, или забрикадироваться вблизи эвакуационных ворот. Ожидайте прибытия мобильной оперативной группы.
alert-level-gray = Фиолетовый
alert-level-gray-announcement = Система Безопасности Комплекса зафиксировала несанкционированное проникновение на территорию комплекса группой неизвестных лиц. Службе Безопасности повысить уровень бдительности.
alert-level-gray-instructions = Персоналу комплекса проявлять повышенную бдительность. На территории комплекса возможна деятельность вражеских шпионов или диверсантов.
alert-level-yellow = Жёлтый
alert-level-yellow-announcement = Зафиксировано нарушение условий содержания SCP-объекта. Всему небоевому персоналу проследовать в безопасное место. Службе Безопасности локализовать угрозу.
alert-level-yellow-instructions = Гражданскому персоналу немедленно покинуть Зону Содержания, или-же отдел откуда сбежал SCP-объект.
alert-level-white = Белый
alert-level-white-announcement = Зафиксировано нападение на комплекс. Всему гражданскому персоналу немедленно проследовать в бункер или организовать баррикады на местах. Службе Безопасности подготовится к активным боевым действиям на территории комплекса.
alert-level-white-instructions = Гражданский персонал обязан немедленно проследовать в безопасное место. Ожидайте прибытия Мобильной Оперативной Группы.
alert-level-delta = ССК-122
alert-level-delta-announcement = Инициирована процедура самоуничтожения комплекса. Всему персоналу следовать указаниям Службы Безопасности, или глав отделов.
alert-level-delta-instructions = Обратитесь к главе своего отдела или службе безопасности за дальнейшими подробностями.
alert-level-coldsilver = Хладное Серебро
alert-level-coldsilver-announcement = Инициирована процедура “Хладное Серебро”. Всему персоналу следует в срочном порядке изолировать комплекс и внешние выходы.
alert-level-coldsilver-instructions = Событие класса К; открытие D-блока; ожидание ликвидации отдела по прошествию неопределенного промежутка времени.
alert-level-foxtrot = Фокстрот
alert-level-foxtrot-announcement = На территории комплекса инициирован аварийный протокол “Фокстрот”. Всему персоналу ожидать дальнейших указаний.
alert-level-foxtrot-instructions = Ожидайте указаний Совета-[ДАННЫЕ УДАЛЕНЫ].
```
И текст-объявления для них.
